# -*- coding: utf-8 -*-
"""YOLO_8s_modelo_tomates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ly9SwKG1MqQuB7Xa1sStQfSGYHrAsmpK
"""

import matplotlib.pyplot as plt
import numpy as np

import zipfile

import shutil
import os

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

file_path = '/content/drive/MyDrive/CHERRY TESIS/cherry_yolov8s_database.zip'

# Verificar que el archivo existe
if os.path.exists(file_path):
    print(f"Archivo encontrado: {file_path}")
else:
    print("Archivo no encontrado. Verifica la ruta.")

data = zipfile.ZipFile('/content/drive/MyDrive/CHERRY TESIS/cherry_yolov8s_database.zip', 'r')
data.extractall('/content/cherry_yolov8s_database')

from skimage import io, color
# Leer la imagen a color (suponiendo que el nombre de la imagen es 'imagen_color.jpg')
imagen_color = io.imread('/content/cherry_yolov8s_database/cherry_yolov8s_database/images/test/IMG_20191215_111912_jpg.rf.2a915553ca015d1365c3ef19eaa55e29.jpg')

# Convertir la imagen a escala de grises
imagen_gris = color.rgb2gray(imagen_color)


# Mostrar las dos imágenes: color y en escala de grises
plt.figure(figsize=(10,5))

# Imagen a color
plt.subplot(1, 2, 1)
plt.imshow(imagen_color)
plt.title('Imagen a color')
plt.axis('off')

# Imagen en escala de grises
plt.subplot(1, 2, 2)
plt.imshow(imagen_gris, cmap='gray')
plt.title('Imagen en escala de grises')
plt.axis('off')

plt.show()

!pip install ultralytics

import ultralytics
ultralytics.checks()
from ultralytics import YOLO
from IPython.display import display, Image

config_path = '/content/cherry_yolov8s_database/cherry_yolov8s_database/configura.yaml'
model = YOLO("yolov8s.pt")

model.train(
    data=config_path,
    epochs=150,
    batch=16,
    imgsz=640,
    patience=50,

    optimizer='AdamW',
    lr0=0.001,
    lrf=0.01,

    box=7.5,
    cls=0.5,
    dfl=1.5,

    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=15,
    translate=0.1,
    scale=0.6,
    shear=0,
    flipud=0.5,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.15,
    copy_paste=0.1,

    dropout=0.1,

    device=0,
    workers=4,

    save_period=10,
    project='cherry_training',
    name='yolov8s_optimized'
)

!yolo predict model="/content/cherry_training/yolov8s_optimized/weights/best.pt" source="/content/cherry_yolov8s_database/cherry_yolov8s_database/images/test/0bfaae18-IMG_20250514_085616.jpg"

!yolo predict model="/content/cherry_training/yolov8s_optimized/weights/best.pt" source="/content/cherry_yolov8s_database/cherry_yolov8s_database/images/test" save=True

!zip -r /content/testeo.zip /content/runs/detect/predict2

model = YOLO('/content/cherry_training/yolov8s_optimized/weights/best.pt')

model.export(format="onnx")
model.export(format="tflite")
model.export(format="coreml")
model.export(format="openvino")
model.export(format="torchscript")

model = YOLO('/content/cherry_training/yolov8s_optimized/weights/best.pt')

model.export(format="tflite", imgsz=640, int8=True)

!zip -r /content/datos_ent.zip /content/cherry_training

!zip -r /content/runs.zip /content/runs